  intel-meson-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fc: [ifort]
        cc: [icc]
    env:
      FC: ${{ matrix.fc }}
      CC: ${{ matrix.cc }}
      APT_PACKAGES: >-
        intel-oneapi-compiler-fortran-2022.1.0
        intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic-2022.1.0
        intel-oneapi-mkl-2022.1.0
        intel-oneapi-mkl-devel-2022.1.0

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Meson & Ninja
        run: pip install meson ninja

      - name: Add Intel oneAPI APT repo
        run: |
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          rm GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update

      - name: Install Intel compilers & MKL
        run: |
          sudo apt-get install -y ${APT_PACKAGES}
          source /opt/intel/oneapi/setvars.sh
          echo "FC=ifort" >> $GITHUB_ENV
          echo "CC=icc" >> $GITHUB_ENV

      - name: Configure build (Meson – Intel)
        run: |
          rm -rf ${{ env.BUILD_DIR }} ${{ env.DIST_DIR }}
          source /opt/intel/oneapi/setvars.sh
          meson setup ${{ env.BUILD_DIR }} \
            --buildtype=debug \
            --prefix=$PWD/${{ env.DIST_DIR }} \
            --libdir=lib \
            --warnlevel=0 \
            -Dfortran_link_args="-lifcoremt -static" \
            -Ddefault_library=static

      - name: Build project
        run: ninja -C ${{ env.BUILD_DIR }}

      - name: Install into _dist
        run: meson install -C ${{ env.BUILD_DIR }} --no-rebuild

      - name: Package Intel build
        run: |
          tar cJvf build-intel.tar.xz ${{ env.DIST_DIR }}
          echo "BUILD_PACKAGE=build-intel.tar.xz" >> $GITHUB_ENV

      - name: Upload Intel build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-intel
          path: build-intel.tar.xz
