name: CI

on: [push, pull_request]

env:
  BUILD_DIR: _build

jobs:
  gcc-meson-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fc: [gfortran-12]
        cc: [gcc-12]
    env:
      FC: ${{ matrix.fc }}
      CC: ${{ matrix.cc }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install GCC and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ${{ matrix.fc }} ${{ matrix.cc }} libopenblas-dev
          echo "FC=${{ matrix.fc }}" >> $GITHUB_ENV
          echo "CC=${{ matrix.cc }}" >> $GITHUB_ENV

      - name: Install Python packages
        run: pip install meson ninja

      - name: Configure build (Meson GNU)
        run: meson setup ${{ env.BUILD_DIR }} --prefix=/ --libdir=lib

      - name: Build project
        run: ninja -C ${{ env.BUILD_DIR }}

      - name: Install project
        run: meson install -C ${{ env.BUILD_DIR }} --no-rebuild

      - name: Package build
        run: |
          tar cJvf build-gnu.tar.xz -C / .
          echo "BUILD_PACKAGE=build-gnu.tar.xz" >> $GITHUB_ENV

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: build-gnu
          path: build-gnu.tar.xz


  intel-meson-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        fc: [ifort]
        cc: [icc]
    env:
      FC: ${{ matrix.fc }}
      CC: ${{ matrix.cc }}
      APT_PACKAGES: >-
        intel-oneapi-compiler-fortran-2022.1.0
        intel-oneapi-compiler-dpcpp-cpp-and-cpp-classic-2022.1.0
        intel-oneapi-mkl-2022.1.0
        intel-oneapi-mkl-devel-2022.1.0

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install Meson and Ninja
        run: pip install meson ninja

      - name: Add Intel APT repository
        run: |
          wget https://apt.repos.intel.com/intel-gpg-keys/GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          sudo apt-key add GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          rm GPG-PUB-KEY-INTEL-SW-PRODUCTS-2023.PUB
          echo "deb https://apt.repos.intel.com/oneapi all main" | sudo tee /etc/apt/sources.list.d/oneAPI.list
          sudo apt-get update

      - name: Install Intel oneAPI compilers and MKL
        run: |
          sudo apt-get install -y ${APT_PACKAGES}
          source /opt/intel/oneapi/setvars.sh
          echo "FC=ifort" >> $GITHUB_ENV
          echo "CC=icc" >> $GITHUB_ENV
          printenv >> $GITHUB_ENV

      - name: Configure build (Meson Intel)
        run: |
          source /opt/intel/oneapi/setvars.sh
          meson setup ${{ env.BUILD_DIR }} \
            --prefix=/ --libdir=lib \
            -Dfortran_link_args="-lifcoremt -static" \
            -Ddefault_library=static \
            -Dlapack=mkl

      - name: Build project
        run: ninja -C ${{ env.BUILD_DIR }}

      - name: Install project
        run: |
          DESTDIR=$PWD/install-root meson install -C ${{ env.BUILD_DIR }} --no-rebuild
          tar cJvf build-intel.tar.xz -C install-root .
          echo "BUILD_PACKAGE=build-intel.tar.xz" >> $GITHUB_ENV

      - name: Upload package
        uses: actions/upload-artifact@v4
        with:
          name: build-intel
          path: build-intel.tar.xz
